from django.db import models
from mcms.models import Base, Country

# Models require to integrate CCAvenue payment gateway

Paymentchoices = (
                  ("Pending","Pending"), 
                  ("Success","Success"), 
                  ("Failure", "Failure"), 
                  ("Aborted", "Aborted"), 
                  ("Invalid", "Invalid")
                 )


CurrencyChoices = (
                    ("int-1","int-1"), 
                    ("int-2","int-2"), 
                    ("ind-1","ind-1"), 
                    ("ind-2","ind-2"), 
                    ("ind-3","ind-3"), 
                    ("ind-4","ind-4"), 
                )
class Subscription(Base):
    # Subscription module
    # will store all payment transaction details
    # amount : Amount
    # orderid : Unique ID sent by the merchant(by us) at the time of initiating the transaction.
    # txnid : Unique payment reference number generated by CCAvenue for each order.
    # message : Reason for failure.
    # payment_mode : Mode of payment used by the customer 
    #   Credit Card 
    #   Net banking 
    #   Debit Card 
    #   Cash Card 
    #   Mobile Payment
    # bankref : Reference number generated by the bank for the transaction.
    # status : Status of the transaction.default will Pending
    #   Success
    #   Failure
    #   Aborted
    #   Invalid
    name = models.CharField("Customer name", max_length=200)
    amount = models.CharField("Amount*", max_length=200)
    year = models.CharField("Years of subscription", max_length=200, blank=True, null=True)
    orderid = models.CharField('Unique ID sent by us', max_length=200)
    status = models.CharField('Status of Transaction', max_length=200, choices = Paymentchoices)
    ptype = models.CharField('Type of Transaction', max_length=200, choices = CurrencyChoices, blank=True, null=True)
    message = models.CharField('Failure Message', max_length=500, blank=True, null=True)
    bankref = models.CharField('Bank Reference Number', max_length=500, blank=True, null=True)
    txnid = models.CharField("Transaction Number", max_length=500, blank=True, null=True)
    payment_mode = models.CharField("mode of Payment", max_length=500, blank=True, null=True)
    profession = models.CharField("Profession", max_length=200, blank=True, null=True)
    email = models.CharField('Email', max_length=200, blank=True, null=True)
    phone = models.CharField('Phone', max_length=200, blank=True, null=True)
    address = models.CharField('Address', max_length=500, blank=True, null=True)
    city = models.CharField('City', max_length=500, blank=True, null=True)
    state = models.CharField('State', max_length=500, blank=True, null=True)
    country = models.ForeignKey(Country, blank=True, null=True, on_delete=models.DO_NOTHING)
    pincode = models.CharField('Zip/Pin code', max_length=500, blank=True, null=True)

    def __unicode__(self):
        # returns self order id
        return self.orderid

class BookSubscribers(models.Model):
    name = models.CharField("Book name", max_length=200, blank=True, null=True)
    subscription = models.ForeignKey(Subscription, on_delete=models.DO_NOTHING)
    amount = models.CharField("Amount*", max_length=200, blank=True, null=True)
    language = models.CharField(max_length=150,blank=True,null=True)
    
    def __unicode__(self):
        return self.name
