# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations
import mcms.thumbs
import ckeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '__first__'),
        ('contenttypes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ads',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('position', models.CharField(max_length=200, verbose_name=b'Ad Position*', choices=[(b'top', b'TOP (371 x 126)'), (b'center', b'CENTER 270 x 270'), (b'bottom', b'BOTTOM 270 x 270')])),
                ('name', models.CharField(max_length=200, verbose_name=b'Ad Name*')),
                ('image', mcms.thumbs.ImageWithThumbsField(null=True, upload_to=b'static/%Y/%m/%d', blank=True)),
                ('code', models.TextField(null=True, verbose_name=b'Code Script', blank=True)),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Archive',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=200, verbose_name=b'Name*')),
                ('upload_file', models.FileField(null=True, upload_to=b'static/%Y/%m/%d', blank=True)),
                ('image', mcms.thumbs.ImageWithThumbsField(null=True, upload_to=b'static/%Y/%m/%d', blank=True)),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('article_type', models.IntegerField(default=1, verbose_name=b'Article Type *', choices=[(1, 'Article'), (2, 'Expert Speak'), (3, 'Interview'), (4, 'Case Study'), (5, 'Myths and Facts'), (6, 'Inspirations')])),
                ('headline', models.CharField(max_length=200, null=True, verbose_name=b'Headline', blank=True)),
                ('slug', models.SlugField(max_length=300, verbose_name=b'SEO friendly url, use only aplhabets and hyphen')),
                ('synopsis', models.CharField(max_length=2000, null=True, verbose_name=b'Strap', blank=True)),
                ('byline', models.CharField(max_length=200, null=True, verbose_name=b'Byline / summary', blank=True)),
                ('icon', mcms.thumbs.ImageWithThumbsField(null=True, upload_to=b'static/%Y/%m/%d', blank=True)),
                ('caption', models.CharField(max_length=200, null=True, verbose_name=b'Photo Caption', blank=True)),
                ('description', ckeditor.fields.RichTextField(null=True, blank=True)),
                ('featured', models.BooleanField(default=False)),
                ('meta_title', models.TextField(null=True, verbose_name=b'Meta Page Title', blank=True)),
                ('meta_description', models.TextField(null=True, verbose_name=b'Meta Description', blank=True)),
                ('display_in_frontend', models.BooleanField(default=False)),
                ('listing_order', models.IntegerField(null=True, verbose_name=b'Listing Order', blank=True)),
                ('attach_file', models.FileField(null=True, upload_to=b'static/%Y/%m/%d', blank=True)),
                ('subscriber_only', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=60)),
                ('attach_file', models.FileField(null=True, upload_to=b'static/%Y/%m/%d', blank=True)),
                ('description', models.CharField(max_length=300, null=True, verbose_name=b'Description', blank=True)),
                ('object_id', models.TextField(verbose_name='object ID')),
                ('content_type', models.ForeignKey(related_name='content_type_set_for_attachment', verbose_name='content type', to='contenttypes.ContentType')),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=400, verbose_name=b'City Name')),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='ColumnCategory',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=200, verbose_name=b'Name*')),
                ('slug', models.SlugField(max_length=100, null=True, verbose_name=b'SEO friendly url, use only aplhabets and hyphen', blank=True)),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Columnists',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=200, verbose_name=b'Name*')),
                ('slug', models.SlugField(max_length=100, null=True, verbose_name=b'SEO friendly url, use only aplhabets and hyphen', blank=True)),
                ('image', mcms.thumbs.ImageWithThumbsField(null=True, upload_to=b'static/%Y/%m/%d', blank=True)),
                ('quote', models.TextField(null=True, verbose_name=b'Quote', blank=True)),
                ('link', models.URLField(verbose_name=b'Article url', blank=True)),
                ('category', models.ForeignKey(to='mcms.ColumnCategory')),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Columns',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=200, null=True, verbose_name=b'Headline', blank=True)),
                ('synopsis', models.CharField(max_length=2000, null=True, verbose_name=b'Strap', blank=True)),
                ('byline', models.CharField(max_length=200, null=True, verbose_name=b'Byline / summary', blank=True)),
                ('caption', models.CharField(max_length=200, null=True, verbose_name=b'Photo Caption', blank=True)),
                ('icon', mcms.thumbs.ImageWithThumbsField(null=True, upload_to=b'static/%Y/%m/%d', blank=True)),
                ('description', ckeditor.fields.RichTextField(null=True, blank=True)),
                ('slug', models.SlugField(max_length=300, verbose_name=b'SEO friendly url, use only aplhabets and hyphen')),
                ('featured', models.BooleanField(default=False)),
                ('meta_title', models.TextField(null=True, verbose_name=b'Meta Page Title', blank=True)),
                ('meta_description', models.TextField(null=True, verbose_name=b'Meta Description', blank=True)),
                ('attach_file', models.FileField(null=True, upload_to=b'static/%Y/%m/%d', blank=True)),
                ('columnist', models.ForeignKey(to='mcms.Columnists')),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=200, verbose_name=b'Your Name*')),
                ('email', models.EmailField(max_length=200, verbose_name=b'Your Email*')),
                ('image', mcms.thumbs.ImageWithThumbsField(null=True, upload_to=b'static/%Y/%m/%d', blank=True)),
                ('comment', models.TextField(null=True, verbose_name=b'Your Comment', blank=True)),
                ('publish', models.BooleanField(default=False)),
                ('object_id', models.TextField(verbose_name='object ID')),
                ('content_type', models.ForeignKey(related_name='content_type_set_for_comments', verbose_name='content type', to='contenttypes.ContentType')),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='ConnectWithUs',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=200, verbose_name=b'Name *')),
                ('email', models.EmailField(max_length=75, null=True, blank=True)),
                ('area_of_interest', models.CharField(max_length=200, null=True, verbose_name=b'Area of Intrest *', blank=True)),
                ('message', ckeditor.fields.RichTextField(null=True, blank=True)),
                ('receive_update', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=400, verbose_name=b'Country Name')),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Currentissue',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=200, verbose_name=b'Name*')),
                ('slug', models.SlugField(max_length=100, null=True, verbose_name=b'SEO friendly url, use only aplhabets and hyphen', blank=True)),
                ('image', mcms.thumbs.ImageWithThumbsField(null=True, upload_to=b'static/%Y/%m/%d', blank=True)),
                ('attachment', models.FileField(upload_to=b'static/%Y/%m/%d', null=True, verbose_name=b'Upload Pdf', blank=True)),
                ('text', models.TextField(null=True, verbose_name=b'Text', blank=True)),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='FrontMenu',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=60)),
                ('slug', models.SlugField(max_length=60, null=True, verbose_name=b'SEO friendly url, use only aplhabets and hyphen', blank=True)),
                ('url', models.URLField(null=True, verbose_name=b'Link Url', blank=True)),
                ('listingOrder', models.IntegerField(default=0)),
                ('image', mcms.thumbs.ImageWithThumbsField(null=True, upload_to=b'static/%Y/%m/%d', blank=True)),
                ('headline', models.CharField(max_length=200, null=True, verbose_name=b'Headline', blank=True)),
                ('description', ckeditor.fields.RichTextField(null=True, verbose_name=b'Description', blank=True)),
                ('meta_title', models.TextField(null=True, verbose_name=b'Meta Page Title', blank=True)),
                ('meta_description', models.TextField(null=True, verbose_name=b'Meta Description', blank=True)),
                ('display_in_menu', models.BooleanField(default=True)),
                ('article', models.ManyToManyField(related_name='Related Article', null=True, to='mcms.Article', blank=True)),
                ('faq_category', models.ManyToManyField(related_name='Related Faq', null=True, to='faq.FAQ_Category', blank=True)),
                ('featured_article', models.ForeignKey(related_name='Featured Article', blank=True, to='mcms.Article', null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=200, verbose_name=b'Gallery Name*')),
                ('front_image', mcms.thumbs.ImageWithThumbsField(null=True, upload_to=b'static/%Y/%m/%d', blank=True)),
                ('link', models.CharField(max_length=200, null=True, verbose_name=b'Gallery URL', blank=True)),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Glossary',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('headline', models.TextField(null=True, blank=True)),
                ('question_text', models.TextField(null=True, blank=True)),
                ('answer_text', models.TextField(null=True, blank=True)),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='HomeBanners',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=160)),
                ('description', ckeditor.fields.RichTextField(null=True, blank=True)),
                ('image', mcms.thumbs.ImageWithThumbsField(null=True, upload_to=b'static/%Y/%m/%d', blank=True)),
                ('featured', models.BooleanField(default=True)),
                ('url', models.URLField(null=True, verbose_name=b'Url', blank=True)),
                ('listing_order', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('image', mcms.thumbs.ImageWithThumbsField(help_text=b'Image size should be 930x300 pixels', null=True, upload_to=b'static/%Y/%m/%d', blank=True)),
                ('name', models.CharField(max_length=50, null=True, verbose_name=b'Caption * ', blank=True)),
                ('description', models.CharField(max_length=300, null=True, verbose_name=b'Description', blank=True)),
                ('URL', models.URLField(verbose_name=b'Link url', blank=True)),
                ('object_id', models.TextField(verbose_name='object ID')),
                ('content_type', models.ForeignKey(related_name='content_type_set_for_image', verbose_name='content type', to='contenttypes.ContentType')),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=200, null=True, blank=True)),
                ('description', ckeditor.fields.RichTextField(null=True, blank=True)),
                ('location', models.TextField()),
                ('role', models.CharField(max_length=200, null=True, blank=True)),
                ('slug', models.SlugField(max_length=100, null=True, verbose_name=b'SEO friendly url, use only aplhabets and hyphen', blank=True)),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='KeyWord',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=200, verbose_name=b'Name')),
                ('slug', models.SlugField(max_length=60, verbose_name=b'SEO friendly url, use only aplhabets and hyphen')),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=400, verbose_name=b'Language Name')),
                ('slug', models.SlugField(max_length=100, verbose_name=b'SEO friendly url, use only aplhabets and hyphen')),
                ('code', models.CharField(max_length=400, null=True, verbose_name=b'Language code', blank=True)),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=100)),
                ('image', mcms.thumbs.ImageWithThumbsField(null=True, upload_to=b'static/%Y/%m/%d', blank=True)),
                ('URl', models.URLField(verbose_name=b'Link Url', blank=True)),
                ('description', models.CharField(max_length=300, null=True, verbose_name=b'Description', blank=True)),
                ('object_id', models.TextField(verbose_name='object ID')),
                ('content_type', models.ForeignKey(related_name='content_type_set_for_link', verbose_name='content type', to='contenttypes.ContentType')),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('slug', models.SlugField(max_length=60, verbose_name=b'SEO friendly url, use only aplhabets and hyphen')),
                ('title', models.CharField(max_length=100, verbose_name=b'Title')),
                ('start_date', models.DateTimeField(null=True, verbose_name=b'Start Date', blank=True)),
                ('end_date', models.DateTimeField(null=True, verbose_name=b'End Date', blank=True)),
                ('publish_date', models.DateTimeField(null=True, verbose_name=b'Publish Date', blank=True)),
                ('description', ckeditor.fields.RichTextField(null=True, blank=True)),
                ('link', models.URLField(verbose_name=b'Link Url', blank=True)),
                ('image', mcms.thumbs.ImageWithThumbsField(null=True, upload_to=b'static/%Y/%m/%d', blank=True)),
                ('article', models.ForeignKey(blank=True, to='mcms.Article', null=True)),
                ('language', models.ForeignKey(blank=True, to='mcms.Language', null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='PhotoFeature',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=200, verbose_name=b'Name*')),
                ('image', mcms.thumbs.ImageWithThumbsField(null=True, upload_to=b'static/%Y/%m/%d', blank=True)),
                ('URL', models.URLField(verbose_name=b'Link url', blank=True)),
                ('description', ckeditor.fields.RichTextField(null=True, blank=True)),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='PhotoFeatureImage',
            fields=[
                ('photofeature_ptr', models.OneToOneField(parent_link=True, auto_created=True, primary_key=True, serialize=False, to='mcms.PhotoFeature')),
                ('photo_feature', models.ForeignKey(related_name='Photo Feature of Photo', to='mcms.PhotoFeature')),
            ],
            options={
                'abstract': False,
            },
            bases=('mcms.photofeature',),
        ),
        migrations.CreateModel(
            name='Quotes',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=400, verbose_name=b'Name')),
                ('image', mcms.thumbs.ImageWithThumbsField(null=True, upload_to=b'static/%Y/%m/%d', blank=True)),
                ('designation', models.CharField(max_length=100, null=True, blank=True)),
                ('description', ckeditor.fields.RichTextField(null=True, blank=True)),
                ('link', models.URLField(verbose_name=b'Link', blank=True)),
                ('frontmenu', models.ForeignKey(blank=True, to='mcms.FrontMenu', null=True)),
                ('language', models.ForeignKey(blank=True, to='mcms.Language', null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=400, verbose_name=b'State Name')),
                ('country', models.ForeignKey(to='mcms.Country')),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=100, verbose_name=b'Tag')),
                ('slug', models.SlugField(max_length=60, verbose_name=b'SEO friendly url, use only aplhabets and hyphen')),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=60)),
                ('designation', models.CharField(max_length=30, null=True, blank=True)),
                ('category', models.IntegerField(default=1, verbose_name=b'Category', choices=[(1, 'Board Of Advisors'), (2, 'Board of Directors'), (3, 'Our Team')])),
                ('description', ckeditor.fields.RichTextField(null=True, blank=True)),
                ('quotes', models.CharField(max_length=1600, null=True, blank=True)),
                ('image', mcms.thumbs.ImageWithThumbsField(null=True, upload_to=b'static/%Y/%m/%d', blank=True)),
                ('listingOrder', models.IntegerField(default=0)),
                ('language', models.ForeignKey(blank=True, to='mcms.Language', null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Videos',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=60)),
                ('image', mcms.thumbs.ImageWithThumbsField(null=True, upload_to=b'static/%Y/%m/%d', blank=True)),
                ('summary', models.TextField(max_length=800, null=True, verbose_name=b'Summary', blank=True)),
                ('description', models.TextField(max_length=800, null=True, verbose_name=b'Description', blank=True)),
                ('featured', models.BooleanField(default=True)),
                ('url', models.URLField(verbose_name=b'Video Url', blank=True)),
                ('display_in_home', models.BooleanField(default=False)),
                ('category', models.ForeignKey(blank=True, to='mcms.Category', null=True)),
                ('language', models.ForeignKey(blank=True, to='mcms.Language', null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model,),
        ),
        migrations.AddField(
            model_name='news',
            name='tags',
            field=models.ManyToManyField(to='mcms.Tag', null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='job',
            name='language',
            field=models.ForeignKey(blank=True, to='mcms.Language', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='job',
            name='parent',
            field=models.ForeignKey(blank=True, to='mcms.Job', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='homebanners',
            name='language',
            field=models.ForeignKey(blank=True, to='mcms.Language', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='glossary',
            name='glossary_tags',
            field=models.ManyToManyField(to='mcms.Tag', null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='frontmenu',
            name='keywords',
            field=models.ManyToManyField(to='mcms.KeyWord', null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='frontmenu',
            name='language',
            field=models.ForeignKey(blank=True, to='mcms.Language', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='frontmenu',
            name='parent',
            field=models.ForeignKey(blank=True, to='mcms.FrontMenu', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='frontmenu',
            name='related_videos',
            field=models.ManyToManyField(to='mcms.Videos', null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='columns',
            name='keywords',
            field=models.ManyToManyField(to='mcms.KeyWord', null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='columns',
            name='language',
            field=models.ForeignKey(blank=True, to='mcms.Language', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='columns',
            name='related_videos',
            field=models.ManyToManyField(to='mcms.Videos', null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='columns',
            name='tags',
            field=models.ManyToManyField(to='mcms.Tag', null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='city',
            name='state',
            field=models.ForeignKey(to='mcms.State'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='article',
            name='frontmenu',
            field=models.ForeignKey(related_name='Related FrontMenu', blank=True, to='mcms.FrontMenu', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='article',
            name='keywords',
            field=models.ManyToManyField(to='mcms.KeyWord', null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='article',
            name='language',
            field=models.ForeignKey(blank=True, to='mcms.Language', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='article',
            name='parent',
            field=models.ForeignKey(blank=True, to='mcms.Article', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='article',
            name='related_videos',
            field=models.ManyToManyField(to='mcms.Videos', null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(to='mcms.Tag', null=True, blank=True),
            preserve_default=True,
        ),
    ]
