from django.urls import path, re_path, include
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.http import HttpResponse
from django.conf import settings
from django.conf.urls.static import static
from mcms import views as mcms_views
from mcms import manage_views

# Portal URL Configuration
urlpatterns = [
    path('', mcms_views.home, name='home'),
    path('ckeditor/', include('ckeditor.urls')),
    path('robots.txt', lambda r: HttpResponse("User-agent: *\nAllow: /", content_type="text/plain")),
    path('gallery/', mcms_views.gallery, name='gallery'),
    path('more/', mcms_views.more, name='more'),
    path('search/', mcms_views.search, name='search'),
    path('photo-feature/', mcms_views.photo, name='photo'),
    path('about-us/', mcms_views.about_us, name='about_us'),
    path('photo-feature/<slug:slug>/', mcms_views.photo_feature, name='photo_feature'),
    path('admin/', admin.site.urls),
    path('change-password/', mcms_views.password_change),
    path('password/reset/', auth_views.PasswordResetView.as_view(template_name='registration/my_password_reset_form.html'), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='registration/my_password_reset_done.html'), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='registration/my_password_reset_confirm.html'), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='registration/my_password_reset_complete.html'), name='password_reset_complete'),
    path('', include(('ccavenue.urls', 'ccavenue'), namespace='ccavenue')),
    path('manage-home/', manage_views.home),
    path('column/<slug:slug>/', mcms_views.column, name='column'),
    path('columns/', mcms_views.columns, name='columns'),
    path('column/<slug:cslug>/<slug:slug>/', mcms_views.column_detail, name='column_detail'),
    path('manage/admin', manage_views.adminlogin, name='login'),
    path('adm/logout/', manage_views.adminlogout, name='logout'),
    path('manage/', manage_views.manage),
    path('login/', mcms_views.frontend_login),
    path('newsletter/', mcms_views.newsletter, name='newsletter'),
    path('write-to-us/', mcms_views.write_to_us, name='writetous'),
    path('logout/', mcms_views.signout, name='civil-logout'),
    path('archive/', mcms_views.archive, name='archive'),
    path('manage-section/deactivate/', manage_views.deactivate),
    path('manage-section/delete/', manage_views.delete_func),
    path('manage-section/activate/', manage_views.activate),
    path('manage-section/unpublish/', manage_views.unpublish),
    path('manage-section/publish/', manage_views.publish),
    path('manage-section/comment/<str:publish>/', manage_views.publishcomment),
    path('manage-section/add-article/', manage_views.add_article),
    path('manage-section/edit-article/', manage_views.edit_article),
    path('manage-section/delete-article/', manage_views.delete_article),
    path('manage-section/activate-article/', manage_views.activate_article),
    path('manage-section/add-editor/', manage_views.add_editor),
    path('manage-section/add-image/', manage_views.add_image),
    path('manage-section/edit-image/', manage_views.edit_image),
    path('manage-section/delete-image/', manage_views.delete_image),
    path('manage-section/activate-image/', manage_views.activate_image),
    path('menu-management/', include(('mcms.urls', 'mcms'), namespace='mcms')),
    path('manage-section/add-form/', manage_views.add_form),
    path('manage-section/edit-form/', manage_views.edit_form),
    path('manage-section/change-password/', manage_views.change_password),
    path('manage-section/add-videos/', manage_views.add_videos),
    path('manage-section/edit-videos/', manage_views.edit_videos),
    path('manage-section/delete-videos/', manage_views.delete_videos),
    path('manage-section/activate-videos/', manage_views.activate_videos),
    path('manage-section/add-frontmenu/', manage_views.add_frontmenu),
    path('manage-section/edit-frontmenu/', manage_views.edit_frontmenu),
    path('manage-section/delete-frontmenu/', manage_views.delete_frontmenu),
    path('manage-section/activate-frontmenu/', manage_views.activate_frontmenu),
    path('manage-section/add-our-banners/', manage_views.add_our_banners),
    path('manage-section/edit-our-banners/', manage_views.edit_our_banners),
    path('manage-section/delete-our-banners/', manage_views.delete_our_banners),
    path('manage-section/activate-our-banners/', manage_views.activate_our_banners),
    path('sitemap.xml/', mcms_views.sitemap),
    path('<slug:slug>/', mcms_views.inner, name='inner'),
    path('<slug:slug>/<slug:aslug>/', mcms_views.article, name='article'),
    path('accounts/', include('allauth.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
